- name: Build and push Docker image
  hosts: localhost
  tasks:
    - name: Login to Docker Hub
      docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password | vault }}"

    - name: Build Docker image
      docker_image:
        path: ./Dockerfile
        name: noobuser008/my-image001
        state: present
        buildargs:
          IMAGE_NAME: my-image001
          IMAGE_TAG: latest
        push: yes
      become: true

- name: Deploy to Minikube
  hosts: localhost
  connection: local
  become: false
  gather_facts: false

  tasks:
    - name: Clone GitHub repository
      git:
        repo: https://github.com/NOOBUSER008/realtimeproj-1.git
        dest: /opt/test  # Replace with the actual directory path

    - name: Set Minikube context
      command: kubectl config use-context minikube

    - name: Apply Deployment
      command: kubectl apply -f /opt/test/deployment.yml  # Replace with the actual file path

    - name: Apply Service
      command: kubectl apply -f /opt/test/service.yml  # Replace with the actual file path


