apiVersion: v1
kind: Service
metadata:
  name: service001
spec:
  type: NodePort
  selector:
    app: blue
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30007
